### ISSUE TITLE
Time in data set very low sampling rate? 10^7 microsecond between sample?

### ISSUE THREAD

**Issue by Bart-van-Ingen** [Oxford-step-counter/DataSet#1]
in the readme.md it is indicated that the sampling is in microseconds, however calculating the difference between the different samples in the validation directory (specifically is user1_armband_1506423438471.csv) 10^7 which is 10 seconds. That seems quite long for step detection on accelerometer data. Am I missing something or is the sampling time different or in a different format?

**Comment by dariosalvi78** [comment]
timestamps are in [nanoseconds](https://developer.android.com/reference/android/hardware/SensorEvent)

**Comment by Bart-van-Ingen** [comment]
alright thank you! please change the readme.md file accordingly, so that others will not have this problem as well in the future! :smile:

**Comment by dariosalvi78** [comment]
BTW, we are developing a C version of the algorithm for micro-controllers if that is of your interest.

**Comment by Bart-van-Ingen** [comment]
that sounds interesting! will you be adding it to this set of repos?

**Comment by dariosalvi78** [comment]
that's the plan.
If you want to know more or be involved somehow, please write me an email at dario dot salvi at mau dot se
